services:
  postgres:
    image: postgres:16.4
    restart: always
    container_name: Kanbanager
    environment:
      - POSTGRES_USER=kanbanager
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: